# 1. Database Connection (The Address)
spring.datasource.url=jdbc:postgresql://localhost:5432/vibesync_db
spring.datasource.username=postgres
# REPLACE 'your_password' with the password you created during Postgres installation
spring.datasource.password=Avneesh@2006

# 2. Hibernate Settings (The Translator)
# 'update' means Spring will automatically create tables for you in the DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect